name: Docker

on:
  push:
    branches:
      - main
    paths-ignore:
     - 'README.md'

  # Run tests for any PRs.
  pull_request:
    branches:
      - main
    paths-ignore:
     - 'README.md'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VERSION: latest
  
jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  build-push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: Set Image ID
        id: set-image-id
        run: echo "::set-output name=IMAGE_ID::$(echo ${{ github.repository }} | tr '[A-Z]' '[a-z]')"

      - name: Set up ID for registry
        id: set-rg-id
        run: |
          echo "::set-output name=DOCKER_ID::${{ steps.set-image-id.outputs.IMAGE_ID }}"
          
      - name: Build Image
        run: |
          docker build . --file Dockerfile \
            -t ${{ steps.set-rg-id.outputs.DOCKER_ID }}:$VERSION 

      - name: Push Image
        run: |
          docker push ${{ steps.set-rg-id.outputs.DOCKER_ID }}:$VERSION
